[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
hexboard = {path = "../hexboard" }
hexgametile = {path = "../hexgametile" }
hex2d = "1.1.0"
nannou = "0.18.1"
structopt = "0.3"
log = "0.4"
pretty_env_logger = "0.3"
lazy_static = "1.4"
thiserror = "1.0"
image = "0.24.5"
